version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pokemon-test-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pokemon_test
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: pokemon_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - pokemon-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pokemon_user -d pokemon_test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local

networks:
  pokemon-network:
    driver: bridge
