/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { appControllerGetData } from '../fn/app/app-controller-get-data';
import { AppControllerGetData$Params } from '../fn/app/app-controller-get-data';
import { appControllerGetProtectedData } from '../fn/app/app-controller-get-protected-data';
import { AppControllerGetProtectedData$Params } from '../fn/app/app-controller-get-protected-data';

@Injectable({ providedIn: 'root' })
export class AppService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `appControllerGetData()` */
  static readonly AppControllerGetDataPath = '/api';

  /**
   * Get application data.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appControllerGetData()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetData$Response(params?: AppControllerGetData$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
}>> {
    return appControllerGetData(this.http, this.rootUrl, params, context);
  }

  /**
   * Get application data.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appControllerGetData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetData(params?: AppControllerGetData$Params, context?: HttpContext): Observable<{
'message'?: string;
}> {
    return this.appControllerGetData$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'message'?: string;
}>): {
'message'?: string;
} => r.body)
    );
  }

  /** Path part for operation `appControllerGetProtectedData()` */
  static readonly AppControllerGetProtectedDataPath = '/api/protected';

  /**
   * Protected endpoint requiring Bearer token.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appControllerGetProtectedData()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetProtectedData$Response(params?: AppControllerGetProtectedData$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'message'?: string;
'user'?: {
};
'timestamp'?: string;
}>> {
    return appControllerGetProtectedData(this.http, this.rootUrl, params, context);
  }

  /**
   * Protected endpoint requiring Bearer token.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appControllerGetProtectedData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetProtectedData(params?: AppControllerGetProtectedData$Params, context?: HttpContext): Observable<{
'message'?: string;
'user'?: {
};
'timestamp'?: string;
}> {
    return this.appControllerGetProtectedData$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'message'?: string;
'user'?: {
};
'timestamp'?: string;
}>): {
'message'?: string;
'user'?: {
};
'timestamp'?: string;
} => r.body)
    );
  }

}
