/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaginationDto {

  /**
   * Number of items per page
   */
  limit: number;

  /**
   * Next page number
   */
  next?: number;

  /**
   * Current page number
   */
  page: number;

  /**
   * Previous page number
   */
  prev?: number;

  /**
   * Total number of items
   */
  total: number;
}
