/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaginationDto } from '../models/pagination-dto';
import { PokemonListItemDto } from '../models/pokemon-list-item-dto';
export interface PokemonListDto {

  /**
   * List of Pokémon items
   */
  items: Array<PokemonListItemDto>;

  /**
   * Pagination metadata
   */
  meta: PaginationDto;
}
