/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PokemonListItemDto {

  /**
   * Unique identifier for the Pokémon
   */
  id: string;

  /**
   * Image URL of the Pokémon
   */
  image: string;

  /**
   * Name of the Pokémon
   */
  name: string;

  /**
   * YouTube URL for the Pokémon
   */
  ytbUrl: string;
}
