/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PokemonFavoriteDto {

  /**
   * Favorite ID
   */
  id: string;

  /**
   * Pokemon ID
   */
  pokemonId: string;

  /**
   * User ID
   */
  userId: string;
}
