/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterDto {

  /**
   * Password of the user
   */
  password: string;

  /**
   * Username of the user
   */
  username: string;
}
